# Netlist diff accross design stages

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

from eda_schema.entity import PHASES
from eda_schema.dataset import Dataset
from eda_schema.db import SQLitePickleDB
from eda_schema.utils.netlist_diff import compare_netlists_by_cells, compare_netlists_by_nets

DATASET_DIR = "../../dataset/dataset_openroad_sky130hd_iwls05_v1.1"
dataset = Dataset(SQLitePickleDB(DATASET_DIR))
dataset.load_dataset(netlist_id='id-000001', load_timing_paths=False)

CIRCUITS = sorted(list(set([circuit for circuit, _, _ in dataset])))

## Cell change comparisons between adjacent design stages

In [2]:
data = []
for circuit in CIRCUITS:
    row = {"circuit": circuit}
    for i in range(len(PHASES) - 1):
        phase1, phase2 = PHASES[i], PHASES[i + 1]
        netlist1 = dataset[(circuit, 'id-000001', phase1)]
        netlist2 = dataset[(circuit, 'id-000001', phase2)]
        _, _, comparison_summary = compare_netlists_by_cells(netlist1, netlist2)
        row.update({f"{phase2}_{k}": v for k, v in comparison_summary.items()})
    data.append(row)

cell_change_df = pd.DataFrame(data)

for i in range(len(PHASES) - 1):
    phase1, phase2 = PHASES[i], PHASES[i + 1]
    print(f"initial stage: {phase1}\nfinal stage: {phase2}")

    phase_df = cell_change_df[["circuit"] + [c for c in cell_change_df.columns if phase2 in c]]
    phase_df.columns = [c.replace(phase2+"_", "") for c in phase_df.columns]
    display(phase_df)

initial stage: floorplan
final stage: global_place

,circuit,init_stage_count,final_stage_count,names_match,names_match_stdcell_match,names_match_stdcell_not_match,names_match_stdcell_not_match_resized,names_match_stdcell_not_match_delay,names_match_stdcell_not_match_remaining,names_not_match,names_not_match_clone,names_not_match_buffered,names_not_match_constant_logic,names_not_match_remaining,removed_cell,removed_cell_is_constant_logic
0,ac97_ctrl,6103,6103,6103,6103,0,0,0,0,0,0,0,0,0,0,0
1,aes_core,11462,11462,11462,11462,0,0,0,0,0,0,0,0,0,0,0
2,des3_area,2659,2659,2659,2659,0,0,0,0,0,0,0,0,0,0,0
3,i2c,619,619,619,619,0,0,0,0,0,0,0,0,0,0,0
4,mem_ctrl,5177,5177,5177,5177,0,0,0,0,0,0,0,0,0,0,0
5,pci,12880,12880,12880,12880,0,0,0,0,0,0,0,0,0,0,0
6,sasc,362,362,362,362,0,0,0,0,0,0,0,0,0,0,0
7,simple_spi,479,479,479,479,0,0,0,0,0,0,0,0,0,0,0
8,spi,1553,1553,1553,1553,0,0,0,0,0,0,0,0,0,0,0
9,ss_pcm,299,299,299,299,0,0,0,0,0,0,0,0,0,0,0
10,systemcaes,4780,4780,4780,4780,0,0,0,0,0,0,0,0,0,0,0
11,systemcdes,1387,1387,1387,1387,0,0,0,0,0,0,0,0,0,0,0
12,tv80,4169,4169,4169,4169,0,0,0,0,0,0,0,0,0,0,0
13,usb_funct,9121,9121,9121,9121,0,0,0,0,0,0,0,0,0,0,0
14,usb_phy,347,347,347,347,0,0,0,0,0,0,0,0,0,0,0
15,wb_dma,2212,2212,2212,2212,0,0,0,0,0,0,0,0,0,0,0

initial stage: global_place
final stage: place_resized

,circuit,init_stage_count,final_stage_count,names_match,names_match_stdcell_match,names_match_stdcell_not_match,names_match_stdcell_not_match_resized,names_match_stdcell_not_match_delay,names_match_stdcell_not_match_remaining,names_not_match,names_not_match_clone,names_not_match_buffered,names_not_match_constant_logic,names_not_match_remaining,removed_cell,removed_cell_is_constant_logic
0,ac97_ctrl,6103,6219,6102,3854,2248,2248,0,0,117,0,116,1,0,1,1
1,aes_core,11462,12040,11462,7469,3993,3993,0,0,578,0,578,0,0,0,0
2,des3_area,2659,3007,2659,1907,752,752,0,0,348,0,348,0,0,0,0
3,i2c,619,650,618,456,162,162,0,0,32,0,30,2,0,1,1
4,mem_ctrl,5177,5489,5175,3343,1832,1832,0,0,314,0,306,8,0,2,2
5,pci,12880,13436,12878,10154,2724,2724,0,0,558,0,550,8,0,2,2
6,sasc,362,389,362,246,116,116,0,0,27,0,27,0,0,0,0
7,simple_spi,479,506,479,327,152,152,0,0,27,0,27,0,0,0,0
8,spi,1553,1654,1552,1056,496,496,0,0,102,0,101,1,0,1,1
9,ss_pcm,299,326,299,243,56,56,0,0,27,0,27,0,0,0,0
10,systemcaes,4780,5231,4780,3382,1398,1398,0,0,451,0,451,0,0,0,0
11,systemcdes,1387,1587,1387,901,486,486,0,0,200,0,200,0,0,0,0
12,tv80,4169,4231,4169,2764,1405,1405,0,0,62,0,62,0,0,0,0
13,usb_funct,9121,9441,9119,7619,1500,1500,0,0,322,0,302,20,0,2,2
14,usb_phy,347,379,347,297,50,50,0,0,32,0,32,0,0,0,0
15,wb_dma,2212,2658,2212,1757,455,455,0,0,446,0,446,0,0,0,0

initial stage: place_resized
final stage: detailed_place

,circuit,init_stage_count,final_stage_count,names_match,names_match_stdcell_match,names_match_stdcell_not_match,names_match_stdcell_not_match_resized,names_match_stdcell_not_match_delay,names_match_stdcell_not_match_remaining,names_not_match,names_not_match_clone,names_not_match_buffered,names_not_match_constant_logic,names_not_match_remaining,removed_cell,removed_cell_is_constant_logic
0,ac97_ctrl,6219,6219,6219,6219,0,0,0,0,0,0,0,0,0,0,0
1,aes_core,12040,12040,12040,12040,0,0,0,0,0,0,0,0,0,0,0
2,des3_area,3007,3007,3007,3007,0,0,0,0,0,0,0,0,0,0,0
3,i2c,650,650,650,650,0,0,0,0,0,0,0,0,0,0,0
4,mem_ctrl,5489,5489,5489,5489,0,0,0,0,0,0,0,0,0,0,0
5,pci,13436,13436,13436,13436,0,0,0,0,0,0,0,0,0,0,0
6,sasc,389,389,389,389,0,0,0,0,0,0,0,0,0,0,0
7,simple_spi,506,506,506,506,0,0,0,0,0,0,0,0,0,0,0
8,spi,1654,1654,1654,1654,0,0,0,0,0,0,0,0,0,0,0
9,ss_pcm,326,326,326,326,0,0,0,0,0,0,0,0,0,0,0
10,systemcaes,5231,5231,5231,5231,0,0,0,0,0,0,0,0,0,0,0
11,systemcdes,1587,1587,1587,1587,0,0,0,0,0,0,0,0,0,0,0
12,tv80,4231,4231,4231,4231,0,0,0,0,0,0,0,0,0,0,0
13,usb_funct,9441,9441,9441,9441,0,0,0,0,0,0,0,0,0,0,0
14,usb_phy,379,379,379,379,0,0,0,0,0,0,0,0,0,0,0
15,wb_dma,2658,2658,2658,2658,0,0,0,0,0,0,0,0,0,0,0

initial stage: detailed_place
final stage: cts

,circuit,init_stage_count,final_stage_count,names_match,names_match_stdcell_match,names_match_stdcell_not_match,names_match_stdcell_not_match_resized,names_match_stdcell_not_match_delay,names_match_stdcell_not_match_remaining,names_not_match,names_not_match_clone,names_not_match_buffered,names_not_match_constant_logic,names_not_match_remaining,removed_cell,removed_cell_is_constant_logic
0,ac97_ctrl,6219,6581,6219,6219,0,0,0,0,362,0,362,0,0,0,0
1,aes_core,12040,13442,12040,11902,138,138,0,0,1402,123,1279,0,0,0,0
2,des3_area,3007,3885,3007,2936,71,71,0,0,878,46,832,0,0,0,0
3,i2c,650,717,650,638,12,12,0,0,67,1,66,0,0,0,0
4,mem_ctrl,5489,6172,5489,5442,47,47,0,0,683,22,661,0,0,0,0
5,pci,13436,14099,13436,13427,9,9,0,0,663,29,634,0,0,0,0
6,sasc,389,439,389,382,7,7,0,0,50,0,50,0,0,0,0
7,simple_spi,506,552,506,502,4,4,0,0,46,0,46,0,0,0,0
8,spi,1654,1819,1654,1617,37,37,0,0,165,11,154,0,0,0,0
9,ss_pcm,326,354,326,326,0,0,0,0,28,1,27,0,0,0,0
10,systemcaes,5231,5795,5231,5193,38,38,0,0,564,19,545,0,0,0,0
11,systemcdes,1587,1876,1587,1530,57,57,0,0,289,25,264,0,0,0,0
12,tv80,4231,4491,4231,4219,12,12,0,0,260,14,246,0,0,0,0
13,usb_funct,9441,9615,9441,9440,1,1,0,0,174,0,174,0,0,0,0
14,usb_phy,379,406,379,379,0,0,0,0,27,0,27,0,0,0,0
15,wb_dma,2658,3061,2658,2641,17,17,0,0,403,6,397,0,0,0,0

initial stage: cts
final stage: global_route

,circuit,init_stage_count,final_stage_count,names_match,names_match_stdcell_match,names_match_stdcell_not_match,names_match_stdcell_not_match_resized,names_match_stdcell_not_match_delay,names_match_stdcell_not_match_remaining,names_not_match,names_not_match_clone,names_not_match_buffered,names_not_match_constant_logic,names_not_match_remaining,removed_cell,removed_cell_is_constant_logic
0,ac97_ctrl,6581,6644,6581,6302,279,279,124,0,63,0,63,0,0,0,0
1,aes_core,13442,13837,13442,11050,2392,2392,938,0,395,32,363,0,0,0,0
2,des3_area,3885,3945,3885,2815,1070,1070,629,0,60,4,56,0,0,0,0
3,i2c,717,732,717,622,95,95,46,0,15,0,15,0,0,0,0
4,mem_ctrl,6172,6256,6172,5371,801,801,404,0,84,1,83,0,0,0,0
5,pci,14099,14223,14099,13261,838,838,367,0,124,10,114,0,0,0,0
6,sasc,439,453,439,376,63,63,27,0,14,0,14,0,0,0,0
7,simple_spi,552,564,552,499,53,53,21,0,12,0,12,0,0,0,0
8,spi,1819,1875,1819,1560,259,259,79,0,56,4,52,0,0,0,0
9,ss_pcm,354,362,354,331,23,23,18,0,8,0,8,0,0,0,0
10,systemcaes,5795,5895,5795,4944,851,851,398,0,100,3,97,0,0,0,0
11,systemcdes,1876,1945,1876,1470,406,406,206,0,69,2,67,0,0,0,0
12,tv80,4491,4545,4491,4044,447,447,131,0,54,3,51,0,0,0,0
13,usb_funct,9615,9647,9615,9140,475,475,134,0,32,0,32,0,0,0,0
14,usb_phy,406,424,406,380,26,26,14,0,18,0,18,0,0,0,0
15,wb_dma,3061,3135,3061,2643,418,418,312,0,74,0,74,0,0,0,0

initial stage: global_route
final stage: detailed_route

,circuit,init_stage_count,final_stage_count,names_match,names_match_stdcell_match,names_match_stdcell_not_match,names_match_stdcell_not_match_resized,names_match_stdcell_not_match_delay,names_match_stdcell_not_match_remaining,names_not_match,names_not_match_clone,names_not_match_buffered,names_not_match_constant_logic,names_not_match_remaining,removed_cell,removed_cell_is_constant_logic
0,ac97_ctrl,6644,6644,6644,6644,0,0,0,0,0,0,0,0,0,0,0
1,aes_core,13837,13837,13837,13837,0,0,0,0,0,0,0,0,0,0,0
2,des3_area,3945,3945,3945,3945,0,0,0,0,0,0,0,0,0,0,0
3,i2c,732,732,732,732,0,0,0,0,0,0,0,0,0,0,0
4,mem_ctrl,6256,6256,6256,6256,0,0,0,0,0,0,0,0,0,0,0
5,pci,14223,14223,14223,14223,0,0,0,0,0,0,0,0,0,0,0
6,sasc,453,453,453,453,0,0,0,0,0,0,0,0,0,0,0
7,simple_spi,564,564,564,564,0,0,0,0,0,0,0,0,0,0,0
8,spi,1875,1875,1875,1875,0,0,0,0,0,0,0,0,0,0,0
9,ss_pcm,362,362,362,362,0,0,0,0,0,0,0,0,0,0,0
10,systemcaes,5895,5895,5895,5895,0,0,0,0,0,0,0,0,0,0,0
11,systemcdes,1945,1945,1945,1945,0,0,0,0,0,0,0,0,0,0,0
12,tv80,4545,4545,4545,4545,0,0,0,0,0,0,0,0,0,0,0
13,usb_funct,9647,9647,9647,9647,0,0,0,0,0,0,0,0,0,0,0
14,usb_phy,424,424,424,424,0,0,0,0,0,0,0,0,0,0,0
15,wb_dma,3135,3135,3135,3135,0,0,0,0,0,0,0,0,0,0,0

## Cell change comparisons of post-floorplan designs with downstream design stages

In [3]:
data = []
for circuit in CIRCUITS:
    row = {"circuit": circuit}
    for i in range(len(PHASES) - 1):
        phase1, phase2 = "floorplan", PHASES[i + 1]
        netlist1 = dataset[(circuit, 'id-000001', phase1)]
        netlist2 = dataset[(circuit, 'id-000001', phase2)]
        _, _, comparison_summary = compare_netlists_by_cells(netlist1, netlist2)
        row.update({f"{phase2}_{k}": v for k, v in comparison_summary.items()})
    data.append(row)

cell_change_df = pd.DataFrame(data)

for i in range(len(PHASES) - 1):
    phase1, phase2 = "floorplan", PHASES[i + 1]
    print(f"initial stage: {phase1}\nfinal stage: {phase2}")

    phase_df = cell_change_df[["circuit"] + [c for c in cell_change_df.columns if phase2 in c]]
    phase_df.columns = [c.replace(phase2+"_", "") for c in phase_df.columns]
    display(phase_df)

initial stage: floorplan
final stage: global_place

,circuit,init_stage_count,final_stage_count,names_match,names_match_stdcell_match,names_match_stdcell_not_match,names_match_stdcell_not_match_resized,names_match_stdcell_not_match_delay,names_match_stdcell_not_match_remaining,names_not_match,names_not_match_clone,names_not_match_buffered,names_not_match_constant_logic,names_not_match_remaining,removed_cell,removed_cell_is_constant_logic
0,ac97_ctrl,6103,6103,6103,6103,0,0,0,0,0,0,0,0,0,0,0
1,aes_core,11462,11462,11462,11462,0,0,0,0,0,0,0,0,0,0,0
2,des3_area,2659,2659,2659,2659,0,0,0,0,0,0,0,0,0,0,0
3,i2c,619,619,619,619,0,0,0,0,0,0,0,0,0,0,0
4,mem_ctrl,5177,5177,5177,5177,0,0,0,0,0,0,0,0,0,0,0
5,pci,12880,12880,12880,12880,0,0,0,0,0,0,0,0,0,0,0
6,sasc,362,362,362,362,0,0,0,0,0,0,0,0,0,0,0
7,simple_spi,479,479,479,479,0,0,0,0,0,0,0,0,0,0,0
8,spi,1553,1553,1553,1553,0,0,0,0,0,0,0,0,0,0,0
9,ss_pcm,299,299,299,299,0,0,0,0,0,0,0,0,0,0,0
10,systemcaes,4780,4780,4780,4780,0,0,0,0,0,0,0,0,0,0,0
11,systemcdes,1387,1387,1387,1387,0,0,0,0,0,0,0,0,0,0,0
12,tv80,4169,4169,4169,4169,0,0,0,0,0,0,0,0,0,0,0
13,usb_funct,9121,9121,9121,9121,0,0,0,0,0,0,0,0,0,0,0
14,usb_phy,347,347,347,347,0,0,0,0,0,0,0,0,0,0,0
15,wb_dma,2212,2212,2212,2212,0,0,0,0,0,0,0,0,0,0,0

initial stage: floorplan
final stage: place_resized

,circuit,init_stage_count,final_stage_count,names_match,names_match_stdcell_match,names_match_stdcell_not_match,names_match_stdcell_not_match_resized,names_match_stdcell_not_match_delay,names_match_stdcell_not_match_remaining,names_not_match,names_not_match_clone,names_not_match_buffered,names_not_match_constant_logic,names_not_match_remaining,removed_cell,removed_cell_is_constant_logic
0,ac97_ctrl,6103,6219,6102,3854,2248,2248,0,0,117,0,116,1,0,1,1
1,aes_core,11462,12040,11462,7469,3993,3993,0,0,578,0,578,0,0,0,0
2,des3_area,2659,3007,2659,1907,752,752,0,0,348,0,348,0,0,0,0
3,i2c,619,650,618,456,162,162,0,0,32,0,30,2,0,1,1
4,mem_ctrl,5177,5489,5175,3343,1832,1832,0,0,314,0,306,8,0,2,2
5,pci,12880,13436,12878,10154,2724,2724,0,0,558,0,550,8,0,2,2
6,sasc,362,389,362,246,116,116,0,0,27,0,27,0,0,0,0
7,simple_spi,479,506,479,327,152,152,0,0,27,0,27,0,0,0,0
8,spi,1553,1654,1552,1056,496,496,0,0,102,0,101,1,0,1,1
9,ss_pcm,299,326,299,243,56,56,0,0,27,0,27,0,0,0,0
10,systemcaes,4780,5231,4780,3382,1398,1398,0,0,451,0,451,0,0,0,0
11,systemcdes,1387,1587,1387,901,486,486,0,0,200,0,200,0,0,0,0
12,tv80,4169,4231,4169,2764,1405,1405,0,0,62,0,62,0,0,0,0
13,usb_funct,9121,9441,9119,7619,1500,1500,0,0,322,0,302,20,0,2,2
14,usb_phy,347,379,347,297,50,50,0,0,32,0,32,0,0,0,0
15,wb_dma,2212,2658,2212,1757,455,455,0,0,446,0,446,0,0,0,0

initial stage: floorplan
final stage: detailed_place

,circuit,init_stage_count,final_stage_count,names_match,names_match_stdcell_match,names_match_stdcell_not_match,names_match_stdcell_not_match_resized,names_match_stdcell_not_match_delay,names_match_stdcell_not_match_remaining,names_not_match,names_not_match_clone,names_not_match_buffered,names_not_match_constant_logic,names_not_match_remaining,removed_cell,removed_cell_is_constant_logic
0,ac97_ctrl,6103,6219,6102,3854,2248,2248,0,0,117,0,116,1,0,1,1
1,aes_core,11462,12040,11462,7469,3993,3993,0,0,578,0,578,0,0,0,0
2,des3_area,2659,3007,2659,1907,752,752,0,0,348,0,348,0,0,0,0
3,i2c,619,650,618,456,162,162,0,0,32,0,30,2,0,1,1
4,mem_ctrl,5177,5489,5175,3343,1832,1832,0,0,314,0,306,8,0,2,2
5,pci,12880,13436,12878,10154,2724,2724,0,0,558,0,550,8,0,2,2
6,sasc,362,389,362,246,116,116,0,0,27,0,27,0,0,0,0
7,simple_spi,479,506,479,327,152,152,0,0,27,0,27,0,0,0,0
8,spi,1553,1654,1552,1056,496,496,0,0,102,0,101,1,0,1,1
9,ss_pcm,299,326,299,243,56,56,0,0,27,0,27,0,0,0,0
10,systemcaes,4780,5231,4780,3382,1398,1398,0,0,451,0,451,0,0,0,0
11,systemcdes,1387,1587,1387,901,486,486,0,0,200,0,200,0,0,0,0
12,tv80,4169,4231,4169,2764,1405,1405,0,0,62,0,62,0,0,0,0
13,usb_funct,9121,9441,9119,7619,1500,1500,0,0,322,0,302,20,0,2,2
14,usb_phy,347,379,347,297,50,50,0,0,32,0,32,0,0,0,0
15,wb_dma,2212,2658,2212,1757,455,455,0,0,446,0,446,0,0,0,0

initial stage: floorplan
final stage: cts

,circuit,init_stage_count,final_stage_count,names_match,names_match_stdcell_match,names_match_stdcell_not_match,names_match_stdcell_not_match_resized,names_match_stdcell_not_match_delay,names_match_stdcell_not_match_remaining,names_not_match,names_not_match_clone,names_not_match_buffered,names_not_match_constant_logic,names_not_match_remaining,removed_cell,removed_cell_is_constant_logic
0,ac97_ctrl,6103,6581,6102,3854,2248,2248,0,0,479,0,478,1,0,1,1
1,aes_core,11462,13442,11462,7394,4068,4068,0,0,1980,123,1857,0,0,0,0
2,des3_area,2659,3885,2659,1858,801,801,0,0,1226,46,1180,0,0,0,0
3,i2c,619,717,618,448,170,170,0,0,99,1,96,2,0,1,1
4,mem_ctrl,5177,6172,5175,3318,1857,1857,0,0,997,22,967,8,0,2,2
5,pci,12880,14099,12878,10150,2728,2728,0,0,1221,29,1184,8,0,2,2
6,sasc,362,439,362,246,116,116,0,0,77,0,77,0,0,0,0
7,simple_spi,479,552,479,323,156,156,0,0,73,0,73,0,0,0,0
8,spi,1553,1819,1552,1041,511,511,0,0,267,11,255,1,0,1,1
9,ss_pcm,299,354,299,243,56,56,0,0,55,1,54,0,0,0,0
10,systemcaes,4780,5795,4780,3363,1417,1417,0,0,1015,19,996,0,0,0,0
11,systemcdes,1387,1876,1387,882,505,505,0,0,489,25,464,0,0,0,0
12,tv80,4169,4491,4169,2756,1413,1413,0,0,322,14,308,0,0,0,0
13,usb_funct,9121,9615,9119,7618,1501,1501,0,0,496,0,476,20,0,2,2
14,usb_phy,347,406,347,297,50,50,0,0,59,0,59,0,0,0,0
15,wb_dma,2212,3061,2212,1745,467,467,0,0,849,6,843,0,0,0,0

initial stage: floorplan
final stage: global_route

,circuit,init_stage_count,final_stage_count,names_match,names_match_stdcell_match,names_match_stdcell_not_match,names_match_stdcell_not_match_resized,names_match_stdcell_not_match_delay,names_match_stdcell_not_match_remaining,names_not_match,names_not_match_clone,names_not_match_buffered,names_not_match_constant_logic,names_not_match_remaining,removed_cell,removed_cell_is_constant_logic
0,ac97_ctrl,6103,6644,6102,3803,2299,2299,0,0,542,0,541,1,0,1,1
1,aes_core,11462,13837,11462,6975,4487,4487,0,0,2375,155,2220,0,0,0,0
2,des3_area,2659,3945,2659,1761,898,898,0,0,1286,50,1236,0,0,0,0
3,i2c,619,732,618,438,180,180,0,0,114,1,111,2,0,1,1
4,mem_ctrl,5177,6256,5175,3262,1913,1913,0,0,1081,23,1050,8,0,2,2
5,pci,12880,14223,12878,10004,2874,2874,0,0,1345,39,1298,8,0,2,2
6,sasc,362,453,362,242,120,120,0,0,91,0,91,0,0,0,0
7,simple_spi,479,564,479,308,171,171,0,0,85,0,85,0,0,0,0
8,spi,1553,1875,1552,971,581,581,0,0,323,15,307,1,0,1,1
9,ss_pcm,299,362,299,242,57,57,0,0,63,1,62,0,0,0,0
10,systemcaes,4780,5895,4780,3159,1621,1621,0,0,1115,22,1093,0,0,0,0
11,systemcdes,1387,1945,1387,829,558,558,0,0,558,27,531,0,0,0,0
12,tv80,4169,4545,4169,2637,1532,1532,0,0,376,17,359,0,0,0,0
13,usb_funct,9121,9647,9119,7424,1695,1695,0,0,528,0,508,20,0,2,2
14,usb_phy,347,424,347,292,55,55,0,0,77,0,77,0,0,0,0
15,wb_dma,2212,3135,2212,1710,502,502,0,0,923,6,917,0,0,0,0

initial stage: floorplan
final stage: detailed_route

,circuit,init_stage_count,final_stage_count,names_match,names_match_stdcell_match,names_match_stdcell_not_match,names_match_stdcell_not_match_resized,names_match_stdcell_not_match_delay,names_match_stdcell_not_match_remaining,names_not_match,names_not_match_clone,names_not_match_buffered,names_not_match_constant_logic,names_not_match_remaining,removed_cell,removed_cell_is_constant_logic
0,ac97_ctrl,6103,6644,6102,3803,2299,2299,0,0,542,0,541,1,0,1,1
1,aes_core,11462,13837,11462,6975,4487,4487,0,0,2375,155,2220,0,0,0,0
2,des3_area,2659,3945,2659,1761,898,898,0,0,1286,50,1236,0,0,0,0
3,i2c,619,732,618,438,180,180,0,0,114,1,111,2,0,1,1
4,mem_ctrl,5177,6256,5175,3262,1913,1913,0,0,1081,23,1050,8,0,2,2
5,pci,12880,14223,12878,10004,2874,2874,0,0,1345,39,1298,8,0,2,2
6,sasc,362,453,362,242,120,120,0,0,91,0,91,0,0,0,0
7,simple_spi,479,564,479,308,171,171,0,0,85,0,85,0,0,0,0
8,spi,1553,1875,1552,971,581,581,0,0,323,15,307,1,0,1,1
9,ss_pcm,299,362,299,242,57,57,0,0,63,1,62,0,0,0,0
10,systemcaes,4780,5895,4780,3159,1621,1621,0,0,1115,22,1093,0,0,0,0
11,systemcdes,1387,1945,1387,829,558,558,0,0,558,27,531,0,0,0,0
12,tv80,4169,4545,4169,2637,1532,1532,0,0,376,17,359,0,0,0,0
13,usb_funct,9121,9647,9119,7424,1695,1695,0,0,528,0,508,20,0,2,2
14,usb_phy,347,424,347,292,55,55,0,0,77,0,77,0,0,0,0
15,wb_dma,2212,3135,2212,1710,502,502,0,0,923,6,917,0,0,0,0

## Net change comparisons between adjacent design stages (up till detailed place)

In [4]:
data = []
for circuit in CIRCUITS:
    row = {"circuit": circuit}
    for i in range(len(PHASES[:4]) - 1):
        phase1, phase2 = PHASES[i], PHASES[i + 1]
        netlist1 = dataset[(circuit, 'id-000001', phase1)]
        netlist2 = dataset[(circuit, 'id-000001', phase2)]
        _, _, comparison_summary = compare_netlists_by_nets(netlist1, netlist2)
        row.update({f"{phase2}_{k}": v for k, v in comparison_summary.items()})
    data.append(row)

cell_change_df = pd.DataFrame(data)

for i in range(len(PHASES[:4]) - 1):
    phase1, phase2 = PHASES[i], PHASES[i + 1]
    print(f"initial stage: {phase1}\nfinal stage: {phase2}")

    phase_df = cell_change_df[["circuit"] + [c for c in cell_change_df.columns if phase2 in c]]
    phase_df.columns = [c.replace(phase2+"_", "") for c in phase_df.columns]
    display(phase_df)

initial stage: floorplan
final stage: global_place

,circuit,init_stage_count,final_stage_count,names_match,names_match_neighbors_match,names_match_neighbors_not_match,names_match_neighbors_not_match_resized,names_match_neighbors_not_match_delay,names_match_neighbors_not_match_buffered,names_match_neighbors_not_match_remaining,names_not_match,names_not_match_buffer_added,names_not_match_buffer_added_output,names_not_match_conb,names_not_match_remaining,removed_net
0,ac97_ctrl,6386,6386,6386,6386,0,0,0,0,0,0,0,0,0,0,0
1,aes_core,12152,12152,12152,12152,0,0,0,0,0,0,0,0,0,0,0
2,des3_area,3211,3211,3211,3211,0,0,0,0,0,0,0,0,0,0,0
3,i2c,680,680,680,680,0,0,0,0,0,0,0,0,0,0,0
4,mem_ctrl,5602,5602,5602,5602,0,0,0,0,0,0,0,0,0,0,0
5,pci,13505,13505,13505,13505,0,0,0,0,0,0,0,0,0,0,0
6,sasc,413,413,413,413,0,0,0,0,0,0,0,0,0,0,0
7,simple_spi,533,533,533,533,0,0,0,0,0,0,0,0,0,0,0
8,spi,1725,1725,1725,1725,0,0,0,0,0,0,0,0,0,0,0
9,ss_pcm,348,348,348,348,0,0,0,0,0,0,0,0,0,0,0
10,systemcaes,5445,5445,5445,5445,0,0,0,0,0,0,0,0,0,0,0
11,systemcdes,1726,1726,1726,1726,0,0,0,0,0,0,0,0,0,0,0
12,tv80,4355,4355,4355,4355,0,0,0,0,0,0,0,0,0,0,0
13,usb_funct,10068,10068,10068,10068,0,0,0,0,0,0,0,0,0,0,0
14,usb_phy,404,404,404,404,0,0,0,0,0,0,0,0,0,0,0
15,wb_dma,2903,2903,2903,2903,0,0,0,0,0,0,0,0,0,0,0

initial stage: global_place
final stage: place_resized

,circuit,init_stage_count,final_stage_count,names_match,names_match_neighbors_match,names_match_neighbors_not_match,names_match_neighbors_not_match_resized,names_match_neighbors_not_match_delay,names_match_neighbors_not_match_buffered,names_match_neighbors_not_match_remaining,names_not_match,names_not_match_buffer_added,names_not_match_buffer_added_output,names_not_match_conb,names_not_match_remaining,removed_net
0,ac97_ctrl,6386,6502,6385,1917,4468,4362,0,105,1,117,69,47,1,0,1
1,aes_core,12152,12730,12152,5461,6691,6199,0,492,0,578,449,129,0,0,0
2,des3_area,3211,3559,3211,1435,1776,1448,0,328,0,348,284,64,0,0,0
3,i2c,680,711,679,383,296,265,0,30,1,32,18,12,2,0,1
4,mem_ctrl,5602,5914,5600,2345,3255,2974,0,280,1,314,160,146,8,0,2
5,pci,13505,14061,13503,8263,5240,4833,0,405,2,558,350,200,8,0,2
6,sasc,413,440,413,181,232,205,0,27,0,27,15,12,0,0,0
7,simple_spi,533,560,533,225,308,281,0,27,0,27,15,12,0,0,0
8,spi,1725,1826,1724,839,885,789,0,95,1,102,57,44,1,0,1
9,ss_pcm,348,375,348,211,137,110,0,27,0,27,18,9,0,0,0
10,systemcaes,5445,5896,5445,2805,2640,2233,0,407,0,451,322,129,0,0,0
11,systemcdes,1726,1926,1726,680,1046,854,0,192,0,200,135,65,0,0,0
12,tv80,4355,4417,4355,2016,2339,2283,0,56,0,62,30,32,0,0,0
13,usb_funct,10068,10388,10066,6947,3119,2881,0,236,2,322,195,107,20,0,2
14,usb_phy,404,436,404,278,126,94,0,32,0,32,14,18,0,0,0
15,wb_dma,2903,3349,2903,1711,1192,754,0,438,0,446,231,215,0,0,0

initial stage: place_resized
final stage: detailed_place

,circuit,init_stage_count,final_stage_count,names_match,names_match_neighbors_match,names_match_neighbors_not_match,names_match_neighbors_not_match_resized,names_match_neighbors_not_match_delay,names_match_neighbors_not_match_buffered,names_match_neighbors_not_match_remaining,names_not_match,names_not_match_buffer_added,names_not_match_buffer_added_output,names_not_match_conb,names_not_match_remaining,removed_net
0,ac97_ctrl,6502,6502,6502,6502,0,0,0,0,0,0,0,0,0,0,0
1,aes_core,12730,12730,12730,12730,0,0,0,0,0,0,0,0,0,0,0
2,des3_area,3559,3559,3559,3559,0,0,0,0,0,0,0,0,0,0,0
3,i2c,711,711,711,711,0,0,0,0,0,0,0,0,0,0,0
4,mem_ctrl,5914,5914,5914,5914,0,0,0,0,0,0,0,0,0,0,0
5,pci,14061,14061,14061,14061,0,0,0,0,0,0,0,0,0,0,0
6,sasc,440,440,440,440,0,0,0,0,0,0,0,0,0,0,0
7,simple_spi,560,560,560,560,0,0,0,0,0,0,0,0,0,0,0
8,spi,1826,1826,1826,1826,0,0,0,0,0,0,0,0,0,0,0
9,ss_pcm,375,375,375,375,0,0,0,0,0,0,0,0,0,0,0
10,systemcaes,5896,5896,5896,5896,0,0,0,0,0,0,0,0,0,0,0
11,systemcdes,1926,1926,1926,1926,0,0,0,0,0,0,0,0,0,0,0
12,tv80,4417,4417,4417,4417,0,0,0,0,0,0,0,0,0,0,0
13,usb_funct,10388,10388,10388,10388,0,0,0,0,0,0,0,0,0,0,0
14,usb_phy,436,436,436,436,0,0,0,0,0,0,0,0,0,0,0
15,wb_dma,3349,3349,3349,3349,0,0,0,0,0,0,0,0,0,0,0

## Net change comparisons of post-floorplan designs with downstream design stages (up till detailed place)

In [5]:
data = []
for circuit in CIRCUITS:
    row = {"circuit": circuit}
    for i in range(len(PHASES[:4]) - 1):
        phase1, phase2 = "floorplan", PHASES[i + 1]
        netlist1 = dataset[(circuit, 'id-000001', phase1)]
        netlist2 = dataset[(circuit, 'id-000001', phase2)]
        _, _, comparison_summary = compare_netlists_by_nets(netlist1, netlist2)
        row.update({f"{phase2}_{k}": v for k, v in comparison_summary.items()})
    data.append(row)

cell_change_df = pd.DataFrame(data)

for i in range(len(PHASES[:4]) - 1):
    phase1, phase2 = "floorplan", PHASES[i + 1]
    print(f"initial stage: {phase1}\nfinal stage: {phase2}")

    phase_df = cell_change_df[["circuit"] + [c for c in cell_change_df.columns if phase2 in c]]
    phase_df.columns = [c.replace(phase2+"_", "") for c in phase_df.columns]
    display(phase_df)

initial stage: floorplan
final stage: global_place

,circuit,init_stage_count,final_stage_count,names_match,names_match_neighbors_match,names_match_neighbors_not_match,names_match_neighbors_not_match_resized,names_match_neighbors_not_match_delay,names_match_neighbors_not_match_buffered,names_match_neighbors_not_match_remaining,names_not_match,names_not_match_buffer_added,names_not_match_buffer_added_output,names_not_match_conb,names_not_match_remaining,removed_net
0,ac97_ctrl,6386,6386,6386,6386,0,0,0,0,0,0,0,0,0,0,0
1,aes_core,12152,12152,12152,12152,0,0,0,0,0,0,0,0,0,0,0
2,des3_area,3211,3211,3211,3211,0,0,0,0,0,0,0,0,0,0,0
3,i2c,680,680,680,680,0,0,0,0,0,0,0,0,0,0,0
4,mem_ctrl,5602,5602,5602,5602,0,0,0,0,0,0,0,0,0,0,0
5,pci,13505,13505,13505,13505,0,0,0,0,0,0,0,0,0,0,0
6,sasc,413,413,413,413,0,0,0,0,0,0,0,0,0,0,0
7,simple_spi,533,533,533,533,0,0,0,0,0,0,0,0,0,0,0
8,spi,1725,1725,1725,1725,0,0,0,0,0,0,0,0,0,0,0
9,ss_pcm,348,348,348,348,0,0,0,0,0,0,0,0,0,0,0
10,systemcaes,5445,5445,5445,5445,0,0,0,0,0,0,0,0,0,0,0
11,systemcdes,1726,1726,1726,1726,0,0,0,0,0,0,0,0,0,0,0
12,tv80,4355,4355,4355,4355,0,0,0,0,0,0,0,0,0,0,0
13,usb_funct,10068,10068,10068,10068,0,0,0,0,0,0,0,0,0,0,0
14,usb_phy,404,404,404,404,0,0,0,0,0,0,0,0,0,0,0
15,wb_dma,2903,2903,2903,2903,0,0,0,0,0,0,0,0,0,0,0

initial stage: floorplan
final stage: place_resized

,circuit,init_stage_count,final_stage_count,names_match,names_match_neighbors_match,names_match_neighbors_not_match,names_match_neighbors_not_match_resized,names_match_neighbors_not_match_delay,names_match_neighbors_not_match_buffered,names_match_neighbors_not_match_remaining,names_not_match,names_not_match_buffer_added,names_not_match_buffer_added_output,names_not_match_conb,names_not_match_remaining,removed_net
0,ac97_ctrl,6386,6502,6385,1917,4468,4362,0,105,1,117,69,47,1,0,1
1,aes_core,12152,12730,12152,5461,6691,6199,0,492,0,578,449,129,0,0,0
2,des3_area,3211,3559,3211,1435,1776,1448,0,328,0,348,284,64,0,0,0
3,i2c,680,711,679,383,296,265,0,30,1,32,18,12,2,0,1
4,mem_ctrl,5602,5914,5600,2345,3255,2974,0,280,1,314,160,146,8,0,2
5,pci,13505,14061,13503,8263,5240,4833,0,405,2,558,350,200,8,0,2
6,sasc,413,440,413,181,232,205,0,27,0,27,15,12,0,0,0
7,simple_spi,533,560,533,225,308,281,0,27,0,27,15,12,0,0,0
8,spi,1725,1826,1724,839,885,789,0,95,1,102,57,44,1,0,1
9,ss_pcm,348,375,348,211,137,110,0,27,0,27,18,9,0,0,0
10,systemcaes,5445,5896,5445,2805,2640,2233,0,407,0,451,322,129,0,0,0
11,systemcdes,1726,1926,1726,680,1046,854,0,192,0,200,135,65,0,0,0
12,tv80,4355,4417,4355,2016,2339,2283,0,56,0,62,30,32,0,0,0
13,usb_funct,10068,10388,10066,6947,3119,2881,0,236,2,322,195,107,20,0,2
14,usb_phy,404,436,404,278,126,94,0,32,0,32,14,18,0,0,0
15,wb_dma,2903,3349,2903,1711,1192,754,0,438,0,446,231,215,0,0,0

initial stage: floorplan
final stage: detailed_place

,circuit,init_stage_count,final_stage_count,names_match,names_match_neighbors_match,names_match_neighbors_not_match,names_match_neighbors_not_match_resized,names_match_neighbors_not_match_delay,names_match_neighbors_not_match_buffered,names_match_neighbors_not_match_remaining,names_not_match,names_not_match_buffer_added,names_not_match_buffer_added_output,names_not_match_conb,names_not_match_remaining,removed_net
0,ac97_ctrl,6386,6502,6385,1917,4468,4362,0,105,1,117,69,47,1,0,1
1,aes_core,12152,12730,12152,5461,6691,6199,0,492,0,578,449,129,0,0,0
2,des3_area,3211,3559,3211,1435,1776,1448,0,328,0,348,284,64,0,0,0
3,i2c,680,711,679,383,296,265,0,30,1,32,18,12,2,0,1
4,mem_ctrl,5602,5914,5600,2345,3255,2974,0,280,1,314,160,146,8,0,2
5,pci,13505,14061,13503,8263,5240,4833,0,405,2,558,350,200,8,0,2
6,sasc,413,440,413,181,232,205,0,27,0,27,15,12,0,0,0
7,simple_spi,533,560,533,225,308,281,0,27,0,27,15,12,0,0,0
8,spi,1725,1826,1724,839,885,789,0,95,1,102,57,44,1,0,1
9,ss_pcm,348,375,348,211,137,110,0,27,0,27,18,9,0,0,0
10,systemcaes,5445,5896,5445,2805,2640,2233,0,407,0,451,322,129,0,0,0
11,systemcdes,1726,1926,1726,680,1046,854,0,192,0,200,135,65,0,0,0
12,tv80,4355,4417,4355,2016,2339,2283,0,56,0,62,30,32,0,0,0
13,usb_funct,10068,10388,10066,6947,3119,2881,0,236,2,322,195,107,20,0,2
14,usb_phy,404,436,404,278,126,94,0,32,0,32,14,18,0,0,0
15,wb_dma,2903,3349,2903,1711,1192,754,0,438,0,446,231,215,0,0,0